title: Nils Streedain
tagline: "Creative from Portland, OR. I make cool stuff and put it on the internet. Follow me wherever."
description: "The personal blog of Nils Streedain, exploring deep dives into cybersecurity, technology, and DIY projects. This blog features detailed articles on a variety of topics, such as reverse engineering, advanced macOS configurations, and creating efficient Raspberry Pi servers. Each entry not only delves into technical procedures and configurations but also addresses broader themes like cybersecurity practices, open authentication standards, and the importance of open-source solutions in a proprietary-dominated world. Whether you're interested in enhancing your cybersecurity measures, exploring technology DIYs, or understanding complex tech setups, this blog offers valuable insights and step-by-step guides."
url: "https://www.nilsstreedain.com"
  
author:
  name: Nils Streedain
  url: https://www.nilsstreedain.com/

logo: /assets/icons/apple-touch-icon.png

social:
  name: Nils Streedain
  links:
    - https://www.instagram.com/nils.streedain
    - https://github.com/nilsstreedain
    - https://www.youtube.com/c/nilsstreedain
    - https://www.linkedin.com/in/nilsstreedain
    - https://twitter.com/nilsstreedain

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
feed:
  categories:
    - blog

webp:
  enabled: true
  quality: 100
  img_dir: ["/assets/img"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif"]
  regenerate: false
